name: Deploy Project
on:
  push:
  branches:
    - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
  deploy:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: List files
        run: ls -l dist
      - name: Deploy
        run: echo "Deploying..."
