name: Deploy React CSR
on: 
  push:
  workflow_dispatch:
jobs:
  lint: 
    # npm run lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install deps
        run: npm i
      - name: lint
        run: npm run lint
  deploy:  
      runs-on: ubuntu-latest
      steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install deps
        run: npm i
      - name: build
        run: npm run build
      - name: List dist/
        run: ls dist
      - name: Deploy
        run: echo "Deploy..."