name: Deploy Project
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

env:
  KEY: 4564
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install and cache
        uses: ./.github/actions/install-cache
      - name: Build Project
        run: npm run build
      - name: List files
        run: ls -l dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."
