name: Deploy Project
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

env:
  KEY: 4564
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print KEY
        run: echo "KEY value:${{vars.API_KEY}}"
      - name: Print KEY2
        run: echo "KEY2 value:${{secrets.API_KEY2}}"
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies 55
        run: npm i
      - name: Build Project
        run: npm run build
      - name: List files
        run: ls -l dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: Force failed
        run: exit 1

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."

  notify:
    runs-on: ubuntu-latest
    needs: 
      - build
      - deploy
    if: failure()
    steps: 
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build fail by Yam'